### PR TITLE
Release/v5.8.0

### LINKED ISSUE #75: setup.sh xvf3800-intdev failed on a Pi4
I've followed instructions from https://github.com/xmos/vocalfusion-rpi-setup/blob/release/v5.8.0/README.md and the script has failed with a weird error something with /lib/modules. I found that this combination of commands worked for me.
```
sudo sh -c "echo 'arm_64bit=0' >> /boot/config.txt"
sudo reboot
sudo apt update
sudo apt upgrade
sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel
sudo reboot
./setup.sh xvf3800-intdev
```

### PR DESCRIPTION
**Pull request by xluciano**
* Update instructions to allow software update of Raspbian packages
  * Increase crontab delay for copying .asoundrc from 15 to 20 seconds
  
 Closes https://github.com/xmos/vocalfusion-rpi-setup/issues/75

### CODE REVIEW

**Review by mbanth — APPROVED** [review]
Looks okay to me.  Please wait for an approving review by @xhuw before merging.

**Comment by xhuw** [comment]
@uvvpavel  found when going through this process recently that he needed to run:

```
sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel
```

before it would work. might be worth getting that in

**Comment by uvvpavel** [comment]
> 

I've gone through the setup a few more times. I found that we don't need to do 
`sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel`
all it needed is a reboot after
```
sudo apt-get update
sudo apt-get upgrade
```
Doing this upgrade will update the kernel version which won't be shown if running `uname`. Hence the script will try to find /lib/modules/old_kernel which does not exist anymore. Rebooting Pi helps in this case

**Review by xhuw — APPROVED** [review]
Thanks @uvvpavel, changes look good then @lucianomartin

**Pull request merged**
